#!/bin/bash

function getCloneUrl {

python <<END_OF_PYTHON
import json
response = json.load(open('.searchJSON'))
END_OF_PYTHON

}

username="swanyriver"
url="https://api.github.com/search/repositories"
search="?q=$1+user:${username}&sort=updated"

#returned output other than http response is lost, packet information shown	
#htresp=$(curl --write-out %{http_code} --output .jsonsearch -u "$auth" $url -d "$json" )
htresp=$(curl --write-out %{http_code} --output .searchJSON ${url}${search} )
echo $htresp

