#!/bin/bash

function showErrors {
python <<END_OF_PYTHON
import json  
response = json.load(open('.jsongit'))

print response['message']
if 'errors' in response:
  for error in response['errors']:
    if 'message' in error: print error['message']
END_OF_PYTHON
}

function getCloneUrl {

python <<END_OF_PYTHON
import json
response = json.load(open('.searchJSON'))
print response['items'][$1]['ssh_url']
END_OF_PYTHON

}


function getNumResults {

python <<END_OF_PYTHON
import json
response = json.load(open('.searchJSON'))
print response["total_count"]
END_OF_PYTHON

}

username="swanyriver"
url="https://api.github.com/search/repositories"
search="?q=$1+user:${username}&sort=updated"

#returned output other than http response is lost, packet information shown	
#htresp=$(curl --write-out %{http_code} --output .jsonsearch -u "$auth" $url -d "$json" )
htresp=$(curl --write-out %{http_code} --output .searchJSON ${url}${search} )

if [[ $htresp == 200 ]] ; then
	
	numResults=$(getNumResults)
	if [[ $numResults == 0 ]] ; then
		echo "no results returned"
		rm .searchJSON
		exit 1
	fi

	#git clone $(getCloneUrl)
	echo $(getCloneUrl 3)

  #rm .searchJSON
  exit 0
else
	echo "FAILED: github response code $htresp"
	showErrors
  rm .searchJSON
	exit 1
fi