#!/bin/bash

function showErrors {
python <<END_OF_PYTHON
import json  
response = json.load(open('.jsongit'))

print response['message']
if 'errors' in response:
  for error in response['errors']:
    if 'message' in error: print error['message']
END_OF_PYTHON
}

function geturl {

python <<END_OF_PYTHON  
import json
repo = json.load(open('.jsongit'))
#print repo['clone_url']
print repo['ssh_url']
END_OF_PYTHON

}

#auth=$(cat ~/BASH/github.cred)
auth=$(cat /home/brandon/SpringOSU15/WEBDEV/git-creation-script/gitauth)
json="{\"name\":\"$1\", \"description\":\"$2\"}"
url="https://api.github.com/user/repos"

#returned output other than http response is lost, packet information shown	
htresp=$(curl --write-out %{http_code} --output .jsongit -u "$auth" $url -d "$json" )

if [[ $htresp == 201 ]] ; then
	echo "created github repo: $1"
  cloneurl=$(geturl)
  rm .jsongit
  set -e
  git init
  git add -A :/
  git commit -m "first commit"
  git remote add origin $cloneurl
  git push -u origin master
  exit 0
else
	echo "FAILED: github response code $htresp"
	showErrors
  rm .jsongit
	exit 1
fi


