#!/bin/bash

function showErrors {
python <<END_OF_PYTHON
import json  
response = json.load(open('.jsongit'))

print response['message']
if 'errors' in response:
  for error in response['errors']:
    if 'message' in error: print error['message']
END_OF_PYTHON
}

function geturl {

python <<END_OF_PYTHON  
import json
repo = json.load(open('.jsongit'))
print repo['clone_url']
END_OF_PYTHON

}

name=$1
auth=$(cat gitauth)
json="{\"name\":\"$name\", \"description\":\"$2\"}"
url="https://api.github.com/user/repos"

#returned output other than http response is lost, packet information shown	
htresp=$(curl --write-out %{http_code} --output .jsongit -u "$auth" $url -d "$json" )

if [[ $htresp == 201 ]] ; then
	echo "created github repo $name"
else
	echo "FAILED: github response code $htresp"
	showErrors
	exit 1
fi


